name: avia_tickets_search
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  hexcolor: ^3.0.1
  intl: any
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner:
  auto_route_generator: ^7.3.1
  freezed: ^2.5.2
  json_serializable: ^6.6.2
  retrofit_generator: '^8.0.1'

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/offers/
    - assets/images/ticket_offers/
